language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "eS4a5lgnxwlR7ftHpVSkmAP1OGWejwV/0/lOZWZZlaALEIosVjWC18Gsz0HQ2tGc23FVuFAsU9mKp+Z7m3YmKzueivSg4bmz7SncnXtFEw6+gx0GqVzBbxB0kkYdseXQchlVrX35A0e2wAskNdSvKDWNsLCqglfSTG+prC4M1/U="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/niteoaws

