language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "R4N8aZ67d6sIVmz2Qbvn7JgrQEvyegfxb8FgtRsxr6xi9vcXVkSfUrFbEPyYX/kY5gQuaEOVjiF5VHbG/OImhHprAn1ya6z9qxVJBr0hoEIQJlucMKqP+mFw1eKjlMMUmgRMR3FHDc9SiV/+iEuY9Tgub+2V0RsRU4ab+YHEyZU="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/niteoaws

